[project]
site_name = "Tryke"
site_url = "https://tryke.dev/"
site_description = "A Rust-based Python test runner with a Jest-style API"
site_author = "Justin Chapman"
copyright = "Copyright &copy; 2025 Justin Chapman"
repo_url = "https://github.com/thejchap/tryke"
repo_name = "tryke"
extra_css = ["stylesheets/extra.css"]
nav = [
  { "Introduction" = "index.md" },
  { "Guides" = [
    "guides/installation.md",
    "guides/writing-tests.md",
    "guides/running-tests.md",
    "guides/filtering.md",
    "guides/async.md",
    "guides/doctests.md",
    "guides/watch-mode.md",
    "guides/changed-mode.md",
    "guides/graph.md",
    "guides/reporters.md",
    "guides/configuration.md",
    "guides/editor-integration.md",
  ] },
  { "Concepts" = [
    "concepts/discovery.md",
    "concepts/soft-assertions.md",
    "concepts/cases.md",
    "concepts/concurrency.md",
    "concepts/client-server.md",
  ] },
  { "Reference" = [
    "reference/api.md",
    "reference/cli.md",
  ] },
]

[project.plugins.search]
enabled = true

[project.theme.icon]
repo = "fontawesome/brands/github"

[project.theme]
custom_dir = "overrides"
logo = "assets/logo.png"
favicon = "assets/logo.png"
features = [
  "navigation.instant",
  "navigation.sections",
  "navigation.path",
  "search.highlight",
  "navigation.tracking",
  "navigation.tabs",
  "navigation.tabs.sticky",
  "navigation.expand",
  "navigation.path",
  "toc.follow",
  "content.action.edit",
  "content.action.view",
  "content.code.copy",
  "content.code.select",
  "content.code.annotate",

]

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
scheme = "default"
primary = "teal"
accent = "teal"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"
primary = "teal"
accent = "teal"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/thejchap"

[project.plugins.offline]

[project.plugins.mkdocstrings.handlers.python]
paths = ["python"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
show_source = false
show_root_heading = true
show_root_full_path = false
members_order = "source"
merge_init_into_class = true
show_signature_annotations = true
separate_signature = true

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.superfences]
