use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use clap::CommandFactory;

use crate::cli::Cli;

const GENERATED_NOTE: &str =
    "<!-- This file is generated by `cargo run --bin generate-cli-docs --`. -->";

pub fn docs_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join("docs/reference/cli.md")
}

pub fn render_cli_reference() -> String {
    let mut out = String::new();
    out.push_str("# CLI Reference\n\n");
    out.push_str(GENERATED_NOTE);
    out.push_str(
        "\n\nThis reference is generated from the clap comments and attributes in `crates/tryke/src/cli.rs`.\n\n",
    );

    let mut command = Cli::command();
    command.build();
    render_section(&command, &["tryke"], 2, &mut out);

    out
}

pub fn normalize_generated_markdown(content: &str) -> String {
    let content = content.replace("\r\n", "\n");
    let mut normalized = content
        .trim_end()
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n");
    normalized.push('\n');
    normalized
}

fn render_section(command: &clap::Command, path: &[&str], level: usize, out: &mut String) {
    let heading = "#".repeat(level);
    let command_name = path.join(" ");
    let _ = writeln!(out, "{heading} `{command_name}`\n");

    if let Some(about) = command.get_long_about().or_else(|| command.get_about()) {
        let about = about.to_string();
        let about = about.trim();
        if !about.is_empty() {
            let _ = writeln!(out, "{about}\n");
        }
    }

    let mut help_command = command.clone();
    let mut help = Vec::new();
    help_command
        .write_long_help(&mut help)
        .expect("write clap help");
    let help = String::from_utf8(help).expect("clap help is valid utf-8");
    let help = normalize_generated_markdown(help.trim());
    let help = help.trim_end();
    let _ = writeln!(out, "```text\n{help}\n```\n");

    let mut subcommands: Vec<_> = command
        .get_subcommands()
        .filter(|subcommand| !subcommand.is_hide_set() && subcommand.get_name() != "help")
        .collect();
    subcommands.sort_by(|left, right| left.get_name().cmp(right.get_name()));

    for subcommand in subcommands {
        let mut next_path = path.to_vec();
        next_path.push(subcommand.get_name());
        render_section(subcommand, &next_path, level + 1, out);
    }
}
