use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use clap::{Arg, ArgAction, Command, CommandFactory};

use crate::cli::Cli;

const GENERATED_NOTE: &str = "<!-- This file is generated by `cargo run -p tryke_dev --bin generate-cli-docs --`. Edit the doc comments in `crates/tryke/src/cli.rs` instead. -->";

pub fn docs_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join("docs/reference/cli.md")
}

pub fn render_cli_reference() -> String {
    let mut out = String::new();
    out.push_str("# CLI Reference\n\n");
    out.push_str(GENERATED_NOTE);
    out.push_str("\n\n");

    let mut command = Cli::command();
    // Build is required so propagated/global options reach subcommands.
    command.build();

    let mut parents: Vec<&Command> = Vec::new();
    render_command(&command, &mut parents, &mut out);

    out
}

pub fn normalize_generated_markdown(content: &str) -> String {
    let content = content.replace("\r\n", "\n");
    let mut normalized = content
        .trim_end()
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n");
    normalized.push('\n');
    normalized
}

fn render_command<'a>(command: &'a Command, parents: &mut Vec<&'a Command>, out: &mut String) {
    if command.is_hide_set() || command.get_name() == "help" {
        return;
    }

    let qualified = qualified_name(command, parents);
    let level = (parents.len() + 2).min(6);
    let _ = writeln!(out, "{} `{qualified}`\n", "#".repeat(level));

    if let Some(about) = command.get_long_about().or_else(|| command.get_about()) {
        let about = about.to_string();
        let trimmed = about.trim();
        if !trimmed.is_empty() {
            let _ = writeln!(out, "{trimmed}\n");
        }
    }

    let mut command_for_usage = command.clone();
    let usage = command_for_usage
        .render_usage()
        .to_string()
        .trim_start_matches("Usage:")
        .trim()
        .to_string();
    let _ = writeln!(out, "**Usage:**\n\n```text\n{usage}\n```\n");

    let subcommands: Vec<&Command> = command
        .get_subcommands()
        .filter(|sub| !sub.is_hide_set() && sub.get_name() != "help")
        .collect();
    if !subcommands.is_empty() {
        out.push_str("**Commands:**\n\n");
        let mut sorted = subcommands.clone();
        sorted.sort_by_key(|sub| sub.get_name());
        for sub in &sorted {
            let sub_qualified = format!("{qualified} {}", sub.get_name());
            let anchor = anchor_for(&sub_qualified);
            let summary = sub
                .get_about()
                .map(|s| s.to_string())
                .unwrap_or_default()
                .trim()
                .to_string();
            if summary.is_empty() {
                let _ = writeln!(out, "- [`{sub_qualified}`](#{anchor})");
            } else {
                let _ = writeln!(out, "- [`{sub_qualified}`](#{anchor}) — {summary}");
            }
        }
        out.push('\n');
    }

    let positionals: Vec<&Arg> = command
        .get_positionals()
        .filter(|arg| !arg.is_hide_set())
        .collect();
    if !positionals.is_empty() {
        out.push_str("**Arguments:**\n\n");
        for arg in &positionals {
            render_positional(arg, out);
        }
    }

    let options: Vec<&Arg> = command
        .get_arguments()
        .filter(|arg| !arg.is_positional() && !arg.is_hide_set() && !is_help_or_version(arg))
        .collect();
    let mut options = options;
    options.sort_by_key(|a| a.get_long().map(str::to_owned).unwrap_or_default());
    if !options.is_empty() {
        out.push_str("**Options:**\n\n");
        for arg in &options {
            render_option(arg, out);
        }
    }

    parents.push(command);
    let mut nested = subcommands;
    nested.sort_by_key(|sub| sub.get_name());
    for sub in nested {
        render_command(sub, parents, out);
    }
    parents.pop();
}

fn qualified_name(command: &Command, parents: &[&Command]) -> String {
    let mut parts: Vec<&str> = parents.iter().map(|c| c.get_name()).collect();
    parts.push(command.get_name());
    parts.join(" ")
}

fn anchor_for(qualified: &str) -> String {
    qualified
        .chars()
        .filter_map(|c| match c {
            ' ' => Some('-'),
            '`' => None,
            c if c.is_ascii_alphanumeric() || c == '-' => Some(c.to_ascii_lowercase()),
            _ => None,
        })
        .collect()
}

fn render_positional(arg: &Arg, out: &mut String) {
    let name = arg.get_id().to_string().to_uppercase();
    let token = if matches!(arg.get_num_args().map(|n| n.max_values()), Some(n) if n > 1) {
        format!("[{name}]...")
    } else if arg.is_required_set() {
        format!("<{name}>")
    } else {
        format!("[{name}]")
    };
    let _ = writeln!(out, "- `{token}`");
    if let Some(help) = arg.get_long_help().or_else(|| arg.get_help()) {
        write_indented_help(&help.to_string(), out);
    }
    out.push('\n');
}

fn render_option(arg: &Arg, out: &mut String) {
    let mut header = String::new();
    if let Some(short) = arg.get_short() {
        header.push_str(&format!("`-{short}`"));
    }
    if let Some(long) = arg.get_long() {
        if !header.is_empty() {
            header.push_str(", ");
        }
        header.push_str(&format!("`--{long}`"));
    }
    if header.is_empty() {
        return;
    }
    let takes_values = arg
        .get_num_args()
        .unwrap_or_else(|| 1.into())
        .takes_values();
    if takes_values && let Some(values) = arg.get_value_names() {
        for value in values {
            header.push_str(&format!(" `<{value}>`"));
        }
    }

    let _ = writeln!(out, "- {header}");
    if let Some(help) = arg.get_long_help().or_else(|| arg.get_help()) {
        write_indented_help(&help.to_string(), out);
    }

    let possible: Vec<String> = arg
        .get_possible_values()
        .iter()
        .filter(|v| !v.is_hide_set())
        .map(|v| format!("`{}`", v.get_name()))
        .collect();
    if !possible.is_empty() {
        let _ = writeln!(out, "\n  Possible values: {}", possible.join(", "));
    }

    if takes_values {
        let defaults: Vec<String> = arg
            .get_default_values()
            .iter()
            .map(|v| format!("`{}`", v.to_string_lossy()))
            .collect();
        if !defaults.is_empty() {
            let _ = writeln!(out, "\n  Default: {}", defaults.join(", "));
        }
    }

    out.push('\n');
}

fn is_help_or_version(arg: &Arg) -> bool {
    matches!(
        arg.get_action(),
        ArgAction::Help | ArgAction::HelpShort | ArgAction::HelpLong | ArgAction::Version
    )
}

fn write_indented_help(help: &str, out: &mut String) {
    let trimmed = help.trim();
    if trimmed.is_empty() {
        return;
    }
    out.push('\n');
    for line in trimmed.lines() {
        if line.is_empty() {
            out.push('\n');
        } else {
            let _ = writeln!(out, "  {line}");
        }
    }
}
