Output demo.gif
Output demo.gif
Output demo.mp4
Output demo.webm

Set Shell "bash"
Set FontSize 18
Set Width 1200
Set Height 700
Set Theme "TokyoNight"
Set WindowBar Colorful

Hide
Type "(sleep 6 && sed -i '' 's|expect(10 / 3|expect(9 / 3|' tests/test_math.py) &"
Enter
Sleep 500ms
Type "clear"
Enter
Show

Type "uvx tryke watch -v"
Sleep 500ms
Enter
Sleep 10s

Hide
Ctrl+C
Sleep 1s
Type "sed -i '' 's|expect(9 / 3|expect(10 / 3|' tests/test_math.py"
Enter
Sleep 1s
